spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/rostrlink}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 5

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${SPRING_MAIL_HOST:mailhog}
    port: ${SPRING_MAIL_PORT:1025}

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,metrics,loggers

logging:
  level:
    root: INFO
    org.springframework: DEBUG